### ISSUE TITLE
Could not find Chrome for otsarHahayal

### ISSUE THREAD

**Issue by AwesomeSapir** [tomerh2001/israeli-banks-actual-budget-importer#24]
Hello, in the container logs im getting this issue and the container stops running
```
Error otsarHahayal Error: Could not find Chrome (ver. 126.0.6478.126). This can occur if either

 1. you did not perform an installation before running the script (e.g. `npx puppeteer browsers install chrome`) or

 2. your cache path is incorrectly configured (which is: /root/.cache/puppeteer).

For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.

    at ChromeLauncher.resolveExecutablePath (/app/node_modules/puppeteer-core/src/node/ProductLauncher.ts:452:17)

    at ChromeLauncher.executablePath (/app/node_modules/puppeteer-core/src/node/ChromeLauncher.ts:280:19)

    at ChromeLauncher.computeLaunchArguments (/app/node_modules/puppeteer-core/src/node/ChromeLauncher.ts:130:31)

    at ChromeLauncher.launch (/app/node_modules/puppeteer-core/src/node/ProductLauncher.ts:99:35)

    at ChromeLauncher.launch (/app/node_modules/puppeteer-core/src/node/ChromeLauncher.ts:59:18)

    at PuppeteerNode.launch (/app/node_modules/puppeteer-core/src/node/PuppeteerNode.ts:173:27)

    at initializePage (/app/node_modules/israeli-bank-scrapers/src/scrapers/base-scraper-with-browser.ts:165:37)

    at OtsarHahayalScraper.initialize (/app/node_modules/israeli-bank-scrapers/src/scrapers/base-scraper-with-browser.ts:103:29)

    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)

    at async OtsarHahayalScraper.scrape (/app/node_modules/israeli-bank-scrapers/src/scrapers/base-scraper.ts:32:5)
```

This is my compose
```
services:
  actual_server:
    image: docker.io/actualbudget/actual-server:latest
    ports:
      - '5006:5006'
    user: 0:0
    volumes:
      - /data/docker/actual/data:/data
    healthcheck:
      # Enable health check for the instance
      test: ['CMD-SHELL', 'node src/scripts/health-check.js']
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: unless-stopped
    
  importer:
    image: tomerh2001/israeli-banks-actual-budget-importer:latest
    cap_add:
      - SYS_ADMIN
    user: 0:0
    volumes:
      - /data/docker/actual/importer/config.json:/app/config.json
      - /data/docker/actual/importer/cache:/app/cache
      - /data/docker/actual/data:/app/data
      - /data/docker/actual/chrome:/app/chrome-data
```
and this is my config file
```
{
  "actual": {
    "init": {
      "dataDir": "./data",
      "password": "****",
      "serverURL": "https://budget.***"
    },
    "budget": {
      "syncId": "****",
      "password": "****"
    }
  },
  "banks": {
    "otsarHahayal": {
      "actualAccountId": "OtsarHahayal",
      "username": "****",
      "password": "****"
    }
  }
}
```

**Comment by tomerh2001** [comment]
Hey, the automated docker push seems to have stopped working, so the image you loaded isn't the most recent one - fixing

**Comment by AwesomeSapir** [comment]
nope, can you explain how to get the chrome data? maybe i did something wrong?

**Comment by tomerh2001** [comment]
> nope, can you explain how to get the chrome data? maybe i did something wrong?

The process itself generates the Chrome data. It contains cookies (which can be helpful when 2FA is involved in the login process).

What error are you getting? If you receive the same error as in your original message, you're likely not using the latest image

**Comment by AwesomeSapir** [comment]
I even changed my compose file to
```
importer:
    image: tomerh2001/israeli-banks-actual-budget-importer:1.2.4
    cap_add:
      - SYS_ADMIN
    user: 0:0
    volumes:
      - /data/docker/actual/importer/config.json:/app/config.json
      - /data/docker/actual/data:/app/data
```

I'm still getting the same error
Let me know if you need help replicating this issue
